project:
  type: website
  output-dir: docs

website:
  title: "Geovanni-Flores-Portfolio-Website"
  navbar:
    background: "#0038A8"
    left:
      - href: index.qmd
        text: Home
      - href: Marketing-Projects.qmd
        text: Marketing Projects
      - href: Dashboard.qmd
        text: Dashboard
      - href: Analytics.qmd
        text: Analytics
      - href: Presentations.qmd
        text: Presentations
        
format:
  html:
    include-in-header:
      - text: |
          <script async src="https://www.googletagmanager.com/gtag/js?id=G-ETWD1PR7BX"></script>
          <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-ETWD1PR7BX');
          </script>

    theme: cosmo
    css: styles.css
    toc: true

editor: visual
