project:
  type: website

website:
  title: "Geovanni-Flores-Portfolio-Website"
  navbar:
    background: "#0038A8"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Resume.qmd
        text: Resume

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
